# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "27970316e7bb72001b9dd00d1a0bef1d"
name = "chefkatscookies-pickup-fn"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# write_delivery_customizations is required to call deliveryCustomizationCreate
# (used once to activate this function on the store).
scopes = "write_delivery_customizations"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "http://localhost:3456/callback"
]
