api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "pickup-delivery-customization"
type = "function"
uid = "0f983787-ba61-7558-f4ac-7fc2753f6b3d52f3c0e8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
